### ISSUE TITLE
bug: A private message that is still there

### ISSUE THREAD

**Issue by AmisFriends2** [revoltchat/revoltchat-solid-client-monorepo#66] opened 2022-11-11 15:20 UTC
### What happened?

I clicked on the private message I have, impossible to open and it stays like that 
[Screen recording 2022-11-11 16.19.22.webm](https://user-images.githubusercontent.com/79320512/201370440-101b7aae-cf9b-4005-be57-f3761cea2591.webm)

**Comment by insertish** [comment] 2022-11-11 17:07
Duplicate of https://github.com/revoltchat/revite/issues/731
Also this is the wrong repository.

**Closed by insertish** 2022-11-11 17:07 UTC
Labels: bug
